---
title: "image_analysis"
author: "Lufan_Yang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis of image data

```{r}
library(glmmTMB)
library(emmeans)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
```

```{r}
cells <- read.csv("/Users/lufanyang/Desktop/ansc499/bile_acid_img/cell_counts.csv")
cells$filename <- gsub(cells$filename, pattern = ".tiff", replacement = "")
rownames(cells) <- cells$filename
cells$type <- as.factor(unlist(lapply(strsplit(cells$filename, split = "_"), function(x) x[1])))
cells$treatment <- as.factor(unlist(lapply(strsplit(cells$filename, split = "_"), function(x) x[2])))
cells$rep <- as.factor(unlist(lapply(strsplit(cells$filename, split = "_"), function(x) x[3])))
cells$position <- as.factor(unlist(lapply(strsplit(cells$filename, split = "_"), function(x) x[4])))
cells$treatment <- relevel(cells$treatment, ref = "DMSO")
cells$combo <- interaction(cells$type, cells$treatment, sep = "_")
levels(cells$combo) 
```

```{r}
model <- glmmTMB(cell_count ~ combo + (1|rep/position) , family = "poisson", data = cells)
summary(model)
emm <- emmeans(model, ~ combo, type = "response")
summary(emm)
pairs(emm)
```

```{r}

p <- ggplot(cells, aes(x = treatment, y = cell_count, fill = treatment)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.size = 0, alpha = 0.5) +
  geom_jitter(width = 0.1, alpha = 0.5) +
 facet_wrap(~ type, scales = "free_y", nrow = 1) +

  labs(
    x = NULL,
    y = "Cell count per image",
    title = "Cell number distributions under bile acid treatments"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
    axis.title.x = element_text(face = "bold", size = 16),
    axis.title.y = element_text(face = "bold", size = 16),
    axis.text.x = element_text(face = "bold", size = 14),
    axis.text.y = element_text(face = "bold", size = 14),
    legend.position = "none",
    strip.background = element_rect(fill = "#EEEEEE"),
    strip.text = element_text(face = "bold", size = 16)
  )
```



```{r}
p2 <- ggplot(subset(cells,treatment=="DMSO"), aes(x = type, y = cell_count,fill = type)) +
  geom_boxplot(width = 0.5, outlier.size = 0, alpha = 0.5) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  labs(
    x = NULL,
    y = "Cell count per image",
    title = "Cell number distributions under three cell type"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
    axis.title.x = element_text(face = "bold", size = 16),
    axis.title.y = element_text(face = "bold", size = 16),
    axis.text.x = element_text(face = "bold", size = 14),
    axis.text.y = element_text(face = "bold", size = 14),
    legend.position = "none",
    strip.background = element_rect(fill = "#EEEEEE"),
    strip.text = element_text(face = "bold", size = 16)
  )
```


